---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: emoji
  type: text
  config:
    required: false
  label: emoji
- name: metadescription
  type: text
  config:
    required: false
  label: metaDescription
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: summary
  type: text
  config:
    required: false
  label: summary
- name: tags
  type: tag_list
  default: []
  label: tags
